### ISSUE TITLE
Consider testing the kube/mpconfig in the test section

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-kubernetes-microprofile-config#15]
Currently the test section has 2 test case that basically are testing the functionality of the 2 services. There's no relevant tests for the actual kube/mpconfig content for this guide. Let's consider this.

**Comment by yeekangc** [comment]
It can be said that they would be tested indirectly.  Then, it doesn't hurt to explicitly validate the values of what we get from Kubernetes with what MP Config returns.

**Comment by proubatsis** [comment]
My thoughts on how to approach this would be:

1. Modify `name` tests to check a value provided to the tests against what is returned, for example:
```
kubectl create configmap greeting-config --from-literal message=Hello
# Create secret and deploy microservices...
mvn verify -Dname.message=Hello
```
Where the tests would check that `name.message` matches what is in the response.

2. For the `ping` tests, it already tests the configuration. If `ping` was misconfigured then `name` would respond with `401 Unauthorized` because the credentials would be incorrect. We can clarify that this is what is happening in the guide's text.

**Comment by proubatsis** [comment]
PR is ready for review #20

**Comment by proubatsis** [comment]
PR Merged
